package com.dev.core.constants;


public enum ProjectActivityType {
    PROJECT_CREATED,
    PROJECT_UPDATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    PHASE_ADDED,
    PHASE_UPDATED,
    FILE_UPLOADED,
    FILE_DELETED,
    TAG_ADDED,
    TAG_REMOVED,
    TAG_UPDATED,
    BUDGET_UPDATED,
    PROGRESS_UPDATED,
    CLIENT_CHANGED,
    OTHER,
    PHASE_DELETED,
    PHASE_REORDERED,
    PHASE_REMOVED,
    MEMBER_UPDATED,
    SPENT_UPDATED,
    PROJECT_RESTORED,
    PROJECT_ARCHIVED
}
